import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/index'
import gilroy from './font'
import PreviewBlock from '@/components/PreviewBlock'
import ChoosingUs from '@/components/ChoosingUs'
import Catalog from '@/components/Catalog'
import AboutExperiences from '@/components/AboutExperiences'
import AboutMaterials from '@/components/AboutMaterials'
import Reviews from '@/components/Reviews'
import { catalog } from './element/product'
import { testimonials } from './element/testimonials'
import Footer from '@/components/Footer'
import Drawler from '@/components/Drawler'
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={gilroy.className}>
        <Header />
      </header>
      <main className={gilroy.className}>
        <PreviewBlock />
        <ChoosingUs />
        <Catalog catalog={catalog} />
        <AboutExperiences />
        <AboutMaterials />
        <Reviews testimonials={testimonials} />
        <Footer />
      </main>
    </>
  )
}
