import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/index";
import gilroy from "@/staticData/font";
import PreviewBlock from "@/components/PreviewBlock";
import ChoosingUs from "@/components/ChoosingUs";
import Catalog from "@/components/Catalog";
import AboutExperiences from "@/components/AboutExperiences";
import AboutMaterials from "@/components/AboutMaterials";
import Reviews from "@/components/Reviews";
import { catalog } from "@/staticData/product";
import { testimonials } from "@/staticData/testimonials";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={gilroy.className}>
        <Header />
      </header>
      <main className={gilroy.className}>
        <PreviewBlock />
        <ChoosingUs />
        <Catalog catalog={catalog} />
        <AboutExperiences />
        <AboutMaterials />
        <Reviews testimonials={testimonials} />
        <Footer />
      </main>
    </>
  );
}
